- name: install wget
  yum: name=wget
  become: yes
  become_user: root

- name: install easy_install
  shell: wget https://bootstrap.pypa.io/ez_setup.py -O - | python
  become: yes
  become_user: root

- name: install pip
  easy_install: name=pip
  become: yes
  become_user: root

# RHEL doesn't have mysql lib to build the python version of mysql-python
# use the yum version and have virtualenv look at system level site-packages
- name: install mysql-python
  yum: name=MySQL-python
  become: yes
  become_user: root

- name: install venv
  pip: name=virtualenv
  become: yes
  become_user: root

- name: create venv_dir
  file: path={{ venv_dir_prefix }} state=directory
  become: yes
  become_user: "{{ app_user }}"

