- name: deliver nginx.repo
  template: src=nginx.repo dest=/etc/yum.repos.d/
  become: yes
  become_user: root

- name: install nginx
  yum: name=nginx
  become: yes
  become_user: root

# this task creates the venv and inherits the system level site packages
# to get access to mysql-python installed via yum
- name: install gunicorn and venv
  pip:
    name: gunicorn
    virtualenv: "{{ venv }}"
    virtualenv_site_packages: yes
  become: yes
  become_user: "{{ app_user }}"

# TODO make sure the service starts on server restart
#- name: start nginx service
#  service: name=nginx state=started
