- name: get latest artifact from circle
  hosts: localhost
  gather_facts: no
  roles:
  - circle
  tags:
  - download

- name: deploy to AWS
  hosts: localhost
  gather_facts: no
  roles:
  - aws
  tags: aws
