- name: get latest artifact from circle
  hosts: localhost
  gather_facts: no
  roles:
  - circle
  tags:
  - download

- name: create AWS instances
  hosts: localhost
  gather_facts: no
  roles:
  - aws

# this play uses the aws dynamic inventory
- name: deploy to AWS
  hosts: tag_group_asiancops_web
  user: "{{ deploy_user }}"
  roles:
  - web
  tags:
  - deploy

